return{}
-- return {
--   -- https://github.com/williamboman/mason.nvim
--   { 'williamboman/mason.nvim' },
--   dependencies = {
--     -- 这个插件是实现自动配置mason 安装的lsp 与 nvim 的lsp接口
--     -- 对接的
--     -- https://github.com/williamboman/mason-lspconfig.nvim
--     { 'williamboman/mason-lspconfig.nvim' },

--     -- Auto-Install LSPs, linters, formatters, debuggers
--     -- https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim
--     -- 我个人其实不是很理解这个插件有什么用，但是好像好多人都装了
--     -- 就为了确保安装
--     { 'WhoIsSethDaniel/mason-tool-installer.nvim' },

--   },

--   config = function()
--     require('mason').setup({
--       ui = {
--         icons = {
--           package_installed = "✓",
--           package_pending = "➜",
--           package_uninstalled = "✗",
--         },
--       },
--     })
--     -- 这里负责配置这些插件，但是仅仅是配置
--     require('mason-lspconfig').setup({
--       -- Install these LSPs automatically
--       ensure_installed = {
--         'bashls',
--         'cssls',
--         'html',
--         'lua_ls',
--         'jsonls',
--         'lemminx',
--         'marksman',
--         'quick_lint_js',
--         'yamlls',
--         'basedpyright',
--       }
--     })
--     require('mason-tool-installer').setup({
--       -- Install these linters, formatters, debuggers automatically
--       ensure_installed = {
--         'black',
--         'debugpy',
--         'flake8',
--         'isort',
--         'mypy',
--         'pylint',
--       },
--     })
--   end

-- }
